# Generated by Django 6.1.1 on 2026-09-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perene', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='status',
        ),
        migrations.AlterField(
            model_name='produto',
            name='validade',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data'),
        ),
    ]
